const {chromium}=require('playwright');const fs=require('fs');const mock=fs.readFileSync('mockdb.js','utf8');const ok=(c,m)=>console.log((c?"OK   ":"FALHA")+" "+m);
(async()=>{const b=await chromium.launch();const ctx=await b.newContext({viewport:{width:1366,height:900},permissions:['clipboard-read','clipboard-write']});await ctx.route(/googleapis|gstatic/,r=>r.abort());
await ctx.addInitScript(mock+`;window.__mock({},5);const _u=window.claude.use;window.claude.use=async n=>n==="downloads"?{save:async o=>{window.__saved=o}}:_u(n);`);
const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.goto('file://'+__dirname+'/../src/checklist-residencia.html');await p.waitForFunction(()=>typeof saveFac==='function',null,{polling:100});await p.waitForTimeout(400);
await p.evaluate(()=>{const D=n=>fromNum(dnum(today())+n);state["CM-1"]={l:2,last:D(-2),step:1,qc:7,qt:10,sd:[0,2],sv:2,cs:[{t:"Meu sub",d:true}]};hist[D(-1)]={q:10,c:7,e:1};
  saveNote("CM-1","## Nota com acento: pré-eclâmpsia ✓");const e={id:"e1",k:"CM-1",w:"x",r:"y",t:"conceito",s:"fonte",d:today(),rev:0};errors.push(e);
  fac={sems:[{id:"s",name:"2026.2",archived:false}],discs:[{id:"d",semId:"s",name:"Cardio",items:["T:CM-1","O:a"]}],provas:[{id:"p",discId:"d",name:"P1",date:D(9),items:["O:a"],done:[]}],own:{a:{t:"Anatomia",discId:"d"}},crunch:{mode:"on",until:D(3)}};saveFac();commit()});
await p.click('#tabQ');await p.click('#cfgBtn');await p.click('#cfBody .cflink:has-text("Instruções")');await p.waitForTimeout(150);
const sum=await p.textContent('#bkSummary');ok(/1 tema com progresso · 1 anotação · 1 erro no caderno · 1 disciplina · 1 prova/.test(sum),"resumo antes de exportar: "+sum);
await p.click('#bkSave');await p.waitForTimeout(200);
const sv=await p.evaluate(()=>window.__saved);ok(sv&&/^checklist-backup-\d{4}-\d\d-\d\d\.json$/.test(sv.filename),"arquivo: "+(sv&&sv.filename));
const B=JSON.parse(sv.data);
ok(B.app==="checklist-residencia"&&B.format===1&&B.exportedAt,"cabeçalho do backup");
ok(B.data.topics["CM-1"].cs[0].t==="Meu sub"&&B.data.topics["CM-1"].qt===10,"temas com subtópicos próprios e questões");
ok(B.data.notes["CM-1"].includes("pré-eclâmpsia ✓"),"anotações com acentos intactos");
ok(B.data.errors.length===1&&B.data.errors[0].s==="fonte","caderno de erros");
ok(B.data.fac.own.a.t==="Anatomia"&&B.data.fac.crunch.mode==="on","faculdade, temas próprios e modo provas");
ok(Object.keys(B.data.hist).length>=1&&B.data.plan&&B.data.plan.items,"histórico e plano");
ok(typeof B.data.prompt==="string"&&B.data.prompt.length>50,"instruções do gerador");
ok((await p.textContent('#bkMsg')).includes("Arquivos"),"mensagem de sucesso");
await p.click('#bkCopy');await p.waitForTimeout(200);const clip=await p.evaluate(()=>navigator.clipboard.readText());
ok(JSON.parse(clip).data.errors.length===1,"Copiar backup coloca o JSON completo na área de transferência");
ok(!errs.length,"sem erros JS "+errs.join("|"));await p.screenshot({path:'bk.png'});await b.close()})();
