const {chromium,devices}=require('playwright');const fs=require('fs');const mock=fs.readFileSync('mockdb.js','utf8');const ok=(c,m)=>console.log((c?"OK   ":"FALHA")+" "+m);
const FILE=process.argv[2]||'file://'+__dirname+'/../src/checklist-residencia.html';
async function run(name,opts){const b=await chromium.launch();const ctx=await b.newContext(opts);await ctx.route(/googleapis|gstatic/,r=>r.abort());await ctx.addInitScript(mock+`;window.__mock({},5);`);
const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.goto(FILE);await p.waitForFunction(()=>typeof saveFac==='function'&&synced,null,{polling:100});
await p.evaluate(()=>{localStorage.clear();fac={sems:[{id:"s",name:"6° Semestre",archived:false},{id:"s2",name:"5° Semestre",archived:false}],discs:[{id:"d",semId:"s",name:"NCS 6",items:[],info:{},eixos:[],sps:[]}],provas:[],own:{}};facSel="s";saveFac();setView("fac")});
await p.waitForTimeout(300);
const tap=async s=>{const l=p.locator(s).first();if(opts.hasTouch)await l.tap();else await l.click();await p.waitForTimeout(150)};
const cnt=async s=>p.locator(s).count();
console.log("== "+name);await p.evaluate(()=>{facOpenSem.add("s");render()});await tap('#fs-s button:has-text("Ajustes")');
await tap('#fs-s .fsemacts button:has-text("Renomear")');
ok(await cnt('.fren')===1,"abre 1 campo de renomear: "+await cnt('.fren'));
await p.evaluate(()=>render());await p.evaluate(()=>render());
ok(await cnt('.fren')===1,"após re-render continua 1 campo: "+await cnt('.fren'));
await p.locator('[id="fr-sem"]').first().fill('6º Semestre 2026.2');await p.evaluate(()=>render());
ok(await p.locator('[id="fr-sem"]').first().inputValue()==='6º Semestre 2026.2',"texto digitado sobrevive a re-render (sincronização)");
await tap('.fren button[type=submit]');
ok(await p.evaluate(()=>fac.sems[0].name)==='6º Semestre 2026.2',"nome salvo: "+await p.evaluate(()=>fac.sems[0].name));
ok(await cnt('.fren')===0,"campo fecha após salvar: "+await cnt('.fren'));
await tap('#fs-s .fsemacts button:has-text("Renomear")');await tap('#fs-s .fsemacts button:has-text("Renomear")');
ok(await cnt('.fren')===0,"tocar Renomear de novo fecha: "+await cnt('.fren'));
await tap('#fs-s .fsemacts button:has-text("Nomes dos níveis")');
ok(await cnt('.flv')===1,"abre 1 formulário de níveis: "+await cnt('.flv'));
await p.evaluate(()=>render());ok(await cnt('.flv')===1,"re-render mantém 1: "+await cnt('.flv'));
await p.locator('#flv-disc').fill('NCS');await p.locator('#flv-sp').fill('Problema');await p.evaluate(()=>render());
ok(await p.locator('#flv-disc').inputValue()==='NCS',"níveis digitados sobrevivem a re-render");
await tap('.flv button[type=submit]');
ok(JSON.stringify(await p.evaluate(()=>fac.sems[0].lv))==='{"disc":"NCS","sp":"Problema"}',"níveis salvos: "+JSON.stringify(await p.evaluate(()=>fac.sems[0].lv)));
ok(await cnt('.flv')===0,"form fecha após salvar: "+await cnt('.flv'));
ok(/\+ NCS/.test(await p.textContent('#fs-s .fstools')),"botões usam o novo nome");
await tap('#fs-s .fsemacts button:has-text("Renomear")');await tap('#fs-s .fssum');
ok(await cnt('.fren')===0,"fechar a pasta do semestre fecha a edição: "+await cnt('.fren'));
const vw=opts.viewport.width;
await tap('#fs-s .fssum');await tap('#fs-s .fsemacts button:has-text("Nomes dos níveis")');const fb=await p.locator('.flv').boundingBox();
const cw=(await p.locator("#facSems").boundingBox()).width;ok(fb&&fb.width>cw*0.8,"form de níveis ocupa a largura da coluna: "+(fb&&Math.round(fb.width))+"/"+Math.round(cw));
ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"sem rolagem horizontal");
await p.screenshot({path:'t36-'+name+'.png'});
ok(!errs.length,"sem erros JS "+errs.join("|"));await b.close()}
(async()=>{await run('fone',{...devices['iPhone 13'],viewport:{width:390,height:844}});await run('desk',{viewport:{width:1366,height:900}})})();
