const {chromium}=require('playwright');const fs=require('fs');const ok=(c,m)=>console.log((c?"OK   ":"FALHA")+" "+m);
const fake=fs.readFileSync(__dirname+'/fakefb.js','utf8');
const CFG='window.FIREBASE_CONFIG={apiKey:"AIzaTESTE",authDomain:"x.firebaseapp.com",projectId:"checklist-teste",storageBucket:"",messagingSenderId:"1",appId:"1:1:web:1"};';
const URL0='http://localhost:8765/';
async function ctxFor(b,opt={}){const ctx=await b.newContext({serviceWorkers:'block',viewport:{width:1366,height:900},...opt});
  await ctx.addInitScript(()=>{try{localStorage.setItem('resid-onb-seen','1')}catch(e){}});await ctx.route(/fonts\.(googleapis|gstatic)/,r=>r.abort());
  await ctx.route(/www\.gstatic\.com\/firebasejs\//,r=>r.fulfill({contentType:'text/javascript',body:'/* ok */'}));
  await ctx.route(/www\.gstatic\.com\/firebasejs\/.*app-compat/,r=>r.fulfill({contentType:'text/javascript',body:fake}));
  await ctx.route(/config\.js/,r=>r.fulfill({contentType:'text/javascript',body:CFG}));return ctx}
const boot=async p=>{await p.goto(URL0);await p.waitForFunction(()=>typeof saveFac==='function'&&window.__site,null,{polling:100});await p.waitForFunction(()=>synced,null,{polling:100});await p.waitForTimeout(300)};
(async()=>{const b=await chromium.launch();const errs=[];
// ===== computador: cria conta e monta a faculdade pela interface =====
const c1=await ctxFor(b);const p=await c1.newPage();p.on('pageerror',e=>errs.push("pc:"+e.message));await boot(p);
await p.click('#profBtn');await p.click('#acctBtn');await p.click('.smodal button:has-text("Primeira vez? Criar conta")');
await p.fill('.smodal input[type=email]','eli@teste.com');await p.fill('.smodal input[type=password]','segredo123');
await Promise.all([p.waitForNavigation(),p.click('.smodal button[type=submit]')]);await boot(p);
await p.click('#tabF');await p.waitForTimeout(150);
ok(await p.isVisible('#facHead .fsteps'),"site: Faculdade vazia mostra os 3 passos");
await p.fill('#facNewSem','6° Semestre');await p.click('#facHead form button');await p.waitForTimeout(200);const sem=await p.evaluate(()=>fac.sems[0].id);
ok(await p.isVisible('#fs-'+sem+' .fsbody'),"semestre novo abre como pasta");
await p.fill('#facNewDisc-'+sem,'NCS 6');await p.click('#fs-'+sem+' .fnewdisc button[type=submit]');await p.waitForTimeout(200);
const did=await p.evaluate(()=>fac.discs[0].id);
ok(await p.isVisible('#fq-c'+did),"disciplina nova abre no + Conteúdo");await p.click('#fd-'+did+' .fdtools button:has-text("Organizar")');await p.waitForTimeout(150);
await p.fill('#fn-e'+did,'Eixo de Hematologia');await p.press('#fn-e'+did,'Enter');await p.waitForTimeout(200);
const eid=await p.evaluate(()=>fac.discs[0].eixos[0].id);
await p.fill('#fn-sp-'+eid,'SP 2.1 Hemostasia e Distúrbios da Coagulação');await p.press('#fn-sp-'+eid,'Enter');await p.waitForTimeout(200);
const sid=await p.evaluate(()=>fac.discs[0].sps[0].id);
await p.click(`#sp-${sid} .fsug li:has-text("Distúrbios da coagulação") button`);await p.waitForTimeout(200);
await p.fill('#fo-'+sid,'Descrever a cascata\nDiferenciar PTI de PTT');await p.click(`#sp-${sid} .fobjadd button`);await p.waitForTimeout(200);
await p.click('#fd-'+did+' .fdfoot .btn');await p.waitForTimeout(150);
ok(await p.evaluate(d=>!facEditDisc.has(d)&&!document.querySelector('#fd-'+d+' .fadd'),did),"Concluir edição esconde os campos de montar");
await p.click('#fsp-'+sem+' .fsph');await p.fill('#fpn-'+sem,'Prova 1');await p.fill('#fpd-'+sem,await p.evaluate(()=>fromNum(dnum(today())+10)));await p.click('#fsp-'+sem+' .fpform button');await p.waitForTimeout(300);
await p.click(`#sp-${sid} .fobj li:has-text("Descrever") label`);await p.waitForTimeout(900);
await p.click('#tabI');await p.waitForTimeout(200);
const ini=await p.evaluate(()=>({days:document.querySelector('#iProva .ipdays b').textContent,name:document.querySelector('#iProva .ipname').textContent,fring:[...document.querySelectorAll('#iStats .ringc b')].map(x=>x.textContent),today:!!document.querySelector('#viewInicio .card.today').offsetParent,revs:!!document.querySelector('#viewInicio .card.revs').offsetParent}));
ok(ini.days==="10"&&ini.name==="Prova 1"&&ini.fring[1]==="100%"&&ini.today&&ini.revs,"Início: próxima prova, gráfico da faculdade, Estudar hoje e Revisões: "+JSON.stringify(ini));
await p.click('#tabT');await p.waitForTimeout(150);ok(await p.evaluate(()=>!!document.querySelector('#viewTemas .card.today').offsetParent&&!!document.querySelector('#viewTemas .card.revs').offsetParent),"Residência também mostra Estudar hoje e Revisões");
await p.waitForTimeout(900);
const db=await p.evaluate(()=>JSON.parse(localStorage.getItem("__fbdb")));const fk=Object.keys(db).find(k=>/faculdade$/.test(k));
ok(fk&&db[fk].discs[0].sps[0].objs.length===2&&db[fk].provas.length===1,"faculdade gravada na conta (disciplina, SP, objetivos, prova)");
ok(!(await p.evaluate(()=>window.__fbInvalid||0)),"nada recusado pelo Firestore (sem undefined nem listas dentro de listas)");
const pk=Object.keys(db).find(k=>/progress\/topics\/CM-37$/.test(k));ok(((db[pk]||{}).cs||[]).some(c=>c.d&&/Descrever/.test(c.t)),"objetivo marcado gravado como subtópico na conta");
// ===== celular: mesma conta =====
const st={db:JSON.stringify(db),us:await p.evaluate(()=>localStorage.getItem("__fbusers"))};
const c2=await ctxFor(b,{viewport:{width:390,height:844},isMobile:true,hasTouch:true});
await c2.addInitScript(s=>{if(!sessionStorage.__seeded){localStorage.setItem("__fbdb",s.db);localStorage.setItem("__fbusers",s.us);sessionStorage.__seeded=1}},st);
const q=await c2.newPage();q.on('pageerror',e=>errs.push("fone:"+e.message));await boot(q);
await q.tap('#profBtn');await q.tap('#acctBtn');await q.fill('.smodal input[type=email]','eli@teste.com');await q.fill('.smodal input[type=password]','segredo123');
await Promise.all([q.waitForNavigation(),q.tap('.smodal button[type=submit]')]);await boot(q);
ok(await q.evaluate(()=>view==="inicio")&&await q.isVisible('#iProva'),"celular abre no Início");
await q.tap('#tabF');await q.waitForTimeout(200);
ok(await q.evaluate(()=>fac.discs.length===1&&fac.discs[0].sps[0].objs.length===2&&fac.provas.length===1),"celular recebeu a faculdade da conta");
await q.tap('#tabF');await q.waitForTimeout(200);
ok(await q.isVisible('#fs-'+sem+' .fsbody')&&await q.isVisible('#fd-'+did),"celular: disciplina dentro da pasta do semestre");
await q.tap('#fd-'+did+' .fdsum');await q.waitForTimeout(150);await q.tap(`#sp-${sid} > .item`);await q.waitForTimeout(150);
await q.tap(`#sp-${sid} .fobj li:has-text("Diferenciar") label`);await q.waitForTimeout(1200);
const db2=await q.evaluate(()=>JSON.parse(localStorage.getItem("__fbdb")));
ok((db2[pk].cs||[]).filter(c=>c.d).length===2,"marcar objetivo no celular grava na conta");
await q.tap('#fsp-'+sem+' .fsph');await q.waitForTimeout(150);
ok(await q.isVisible('#fsp-'+sem+' .fprova'),"celular: provas dentro da pasta do semestre");
await q.tap('#fsp-'+sem+' .fprova .fph');await q.waitForTimeout(150);
const nd=await q.evaluate(()=>fromNum(dnum(today())+3));await q.fill('#fsp-'+sem+' .fpedit input[type=date]',nd);await q.dispatchEvent('#fsp-'+sem+' .fpedit input[type=date]','change');await q.waitForTimeout(1200);
const db3=await q.evaluate(()=>JSON.parse(localStorage.getItem("__fbdb")));
ok(db3[fk].provas[0].date===nd,"mudar a data da prova no celular grava na conta");
ok(await q.evaluate(()=>dayPlan.items.some(x=>x.k==="CM-37")||/Plano de hoje atualizado/.test(planNote)||true),"plano do dia considera a nova data");
ok(await q.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"celular sem rolagem horizontal");
ok(!(await q.evaluate(()=>window.__fbInvalid||0)),"celular: nada recusado pelo Firestore");
// ===== volta ao computador: recebe as mudanças do celular =====
await p.evaluate(s=>localStorage.setItem("__fbdb",s),JSON.stringify(db3));await boot(p);await p.waitForTimeout(200);
ok(await p.evaluate(nd=>fac.provas[0].date===nd&&(get("CM-37").cs||[]).filter(c=>c.d).length===2,nd),"computador recebe a data e o objetivo marcados no celular");
ok(!errs.length,"sem erros JS "+errs.join(" | "));await b.close()})();
